//! Second-factor and recovery credentials: TOTP (RFC 6238) and a
//! server-generated Diceware passphrase, plus the step-up primitive that
//! gates sensitive account changes.
//!
//! TOTP is an *enhancing second factor* for the password (required after
//! password at login when confirmed). The passphrase is a *standalone
//! strongest factor and recovery anchor* — it can authenticate on its own and
//! is the credential that authorizes password reset and TOTP changes. When a
//! user has no passphrase, sensitive actions fall back to the password.

use chrono::{DateTime, Utc};
use diesel::prelude::*;
use diesel_async::RunQueryDsl;
use rand::Rng;
use totp_rs::{Algorithm, Secret, TOTP};

use crate::models::{
    CredentialPassphraseRow, CredentialTotpRow, NewCredentialPassphrase, NewCredentialTotp,
};
use crate::schema::{credential_passphrase, credential_totp};
use crate::types::*;
use crate::Engine;

const TOTP_DIGITS: usize = 6;
const TOTP_SKEW: u8 = 1;
const TOTP_STEP_SECS: u64 = 30;
const TOTP_ISSUER: &str = "Surge";

const PASSPHRASE_WORDS: usize = 6;
/// EFF large wordlist (7776 words, Diceware-compatible), one word per line.
const WORDLIST: &str = include_str!("eff_large_wordlist.txt");

/// One-time enrollment material handed to the user to load into an
/// authenticator app. The secret is also returned base32-encoded for manual
/// entry; the `otpauth://` URI is what the frontend renders as a QR code.
pub struct TotpEnrollment {
    pub secret_base32: String,
    pub otpauth_uri: String,
}

/// Which factors an identity currently has enrolled (TOTP counts only once
/// confirmed).
#[derive(Debug, Clone, Copy)]
pub struct FactorStatus {
    pub has_totp: bool,
    pub has_passphrase: bool,
}

impl Engine {
    // ---- TOTP ---------------------------------------------------------------

    /// Build a `TOTP` for the given raw secret. `new_unchecked` skips the
    /// length/account validation `new` performs — fine here since the secret
    /// was generated by us and the account label is cosmetic for verification.
    fn totp_for(secret: Vec<u8>, account: String) -> TOTP {
        TOTP::new_unchecked(
            Algorithm::SHA1,
            TOTP_DIGITS,
            TOTP_SKEW,
            TOTP_STEP_SECS,
            secret,
            Some(TOTP_ISSUER.to_string()),
            account,
        )
    }

    fn current_step(now: DateTime<Utc>) -> u64 {
        now.timestamp() as u64 / TOTP_STEP_SECS
    }

    /// Return the TOTP step in `[current-1, current+1]` whose generated code
    /// equals `code`, or `None` if no candidate matches.
    fn matching_step(totp: &TOTP, code: &str, now: DateTime<Utc>) -> Option<u64> {
        let current = Self::current_step(now);
        (current.saturating_sub(1)..=current + 1)
            .find(|&step| totp.generate(step * TOTP_STEP_SECS) == code)
    }

    /// Start TOTP enrollment: generate a secret, store it encrypted and
    /// *unconfirmed* (overwriting any prior unconfirmed enrollment), and return
    /// the provisioning material. Not usable for login until `confirm_totp`.
    pub async fn begin_totp_enrollment(
        &self,
        identity_id: IdentityId,
    ) -> Result<TotpEnrollment, AuthError> {
        // Never overwrite a *confirmed* TOTP: doing so would immediately drop
        // the user's second-factor gate (has_totp filters on confirmed) and
        // invalidate their working authenticator before anything replaces it.
        // Re-configuring means remove-then-enroll (both step-up-gated). A prior
        // *unconfirmed* enrollment is still freely overwritten below.
        if self.has_totp(identity_id).await? {
            return Err(AuthError::Validation(ValidationError::Field {
                field: "totp",
                message: "TOTP already enrolled; remove it before enrolling again".into(),
            }));
        }

        let identity = self.get_identity(identity_id).await?;

        let secret = Secret::generate_secret()
            .to_bytes()
            .map_err(|e| AuthError::Internal(anyhow::anyhow!("totp secret: {e}")))?;
        let totp = TOTP::new(
            Algorithm::SHA1,
            TOTP_DIGITS,
            TOTP_SKEW,
            TOTP_STEP_SECS,
            secret.clone(),
            Some(TOTP_ISSUER.to_string()),
            identity.username.as_str().to_string(),
        )
        .map_err(|e| AuthError::Internal(anyhow::anyhow!("totp build: {e}")))?;

        let encrypted = self.encrypt_secret(&secret)?;
        let now = Utc::now();
        let mut conn = self.conn().await?;

        diesel::insert_into(credential_totp::table)
            .values(&NewCredentialTotp {
                identity_id: *identity_id.as_uuid(),
                secret_encrypted: &encrypted,
                confirmed_at: None,
                last_used_step: None,
                created_at: now,
                updated_at: now,
            })
            .on_conflict(credential_totp::identity_id)
            .do_update()
            .set((
                credential_totp::secret_encrypted.eq(&encrypted),
                credential_totp::confirmed_at.eq::<Option<DateTime<Utc>>>(None),
                credential_totp::last_used_step.eq::<Option<i64>>(None),
                credential_totp::updated_at.eq(now),
            ))
            .execute(&mut conn)
            .await
            .map_err(|e| AuthError::Internal(e.into()))?;

        Ok(TotpEnrollment {
            secret_base32: totp.get_secret_base32(),
            otpauth_uri: totp.get_url(),
        })
    }

    /// Confirm a pending TOTP enrollment by verifying one code; marks it
    /// confirmed and records the used step so the same code can't immediately
    /// be replayed as a login.
    pub async fn confirm_totp(
        &self,
        identity_id: IdentityId,
        code: &str,
    ) -> Result<(), AuthError> {
        let mut conn = self.conn().await?;

        let row: CredentialTotpRow = credential_totp::table
            .find(*identity_id.as_uuid())
            .select(CredentialTotpRow::as_select())
            .first(&mut conn)
            .await
            .map_err(|e| match e {
                diesel::result::Error::NotFound => AuthError::NotFound,
                other => AuthError::Internal(other.into()),
            })?;

        let secret = self.decrypt_secret(&row.secret_encrypted)?;
        let totp = Self::totp_for(secret, String::from("surge"));
        let now = Utc::now();
        let step = Self::matching_step(&totp, code, now).ok_or(AuthError::InvalidCredentials)?;

        diesel::update(credential_totp::table.find(*identity_id.as_uuid()))
            .set((
                credential_totp::confirmed_at.eq(now),
                credential_totp::last_used_step.eq(step as i64),
                credential_totp::updated_at.eq(now),
            ))
            .execute(&mut conn)
            .await
            .map_err(|e| AuthError::Internal(e.into()))?;

        Ok(())
    }

    /// Verify a login-time TOTP code for a *confirmed* enrollment, rejecting
    /// replays of an already-used step (within the skew window).
    pub async fn verify_totp(
        &self,
        identity_id: IdentityId,
        code: &str,
    ) -> Result<(), AuthError> {
        let mut conn = self.conn().await?;

        let row: CredentialTotpRow = credential_totp::table
            .find(*identity_id.as_uuid())
            .filter(credential_totp::confirmed_at.is_not_null())
            .select(CredentialTotpRow::as_select())
            .first(&mut conn)
            .await
            .map_err(|e| match e {
                diesel::result::Error::NotFound => AuthError::InvalidCredentials,
                other => AuthError::Internal(other.into()),
            })?;

        let secret = self.decrypt_secret(&row.secret_encrypted)?;
        let totp = Self::totp_for(secret, String::from("surge"));
        let now = Utc::now();
        let step = Self::matching_step(&totp, code, now).ok_or(AuthError::InvalidCredentials)?;

        // Replay prevention: the matched step must be newer than the last used.
        if let Some(last) = row.last_used_step {
            if (step as i64) <= last {
                return Err(AuthError::InvalidCredentials);
            }
        }

        diesel::update(credential_totp::table.find(*identity_id.as_uuid()))
            .set((
                credential_totp::last_used_step.eq(step as i64),
                credential_totp::updated_at.eq(now),
            ))
            .execute(&mut conn)
            .await
            .map_err(|e| AuthError::Internal(e.into()))?;

        Ok(())
    }

    pub async fn remove_totp(&self, identity_id: IdentityId) -> Result<(), AuthError> {
        let mut conn = self.conn().await?;
        diesel::delete(credential_totp::table.find(*identity_id.as_uuid()))
            .execute(&mut conn)
            .await
            .map_err(|e| AuthError::Internal(e.into()))?;
        Ok(())
    }

    pub async fn has_totp(&self, identity_id: IdentityId) -> Result<bool, AuthError> {
        let mut conn = self.conn().await?;
        let count: i64 = credential_totp::table
            .find(*identity_id.as_uuid())
            .filter(credential_totp::confirmed_at.is_not_null())
            .count()
            .get_result(&mut conn)
            .await
            .map_err(|e| AuthError::Internal(e.into()))?;
        Ok(count > 0)
    }

    // ---- Passphrase ---------------------------------------------------------

    /// Generate a 6-word EFF Diceware passphrase (~77 bits of entropy).
    pub fn generate_passphrase(&self) -> String {
        let words: Vec<&str> = WORDLIST.lines().collect();
        let mut rng = rand::rng();
        (0..PASSPHRASE_WORDS)
            .map(|_| words[rng.random_range(0..words.len())])
            .collect::<Vec<_>>()
            .join(" ")
    }

    /// Fold user-entered passphrases to the canonical form we hash: trimmed,
    /// single-spaced, lowercased (the generated form is already canonical).
    fn canonical_passphrase(input: &str) -> String {
        input.split_whitespace().collect::<Vec<_>>().join(" ").to_lowercase()
    }

    /// Generate a fresh passphrase, store its hash (overwriting any existing
    /// one), and return the plaintext **once** — it is never recoverable after.
    pub async fn set_passphrase(&self, identity_id: IdentityId) -> Result<String, AuthError> {
        let passphrase = self.generate_passphrase();
        let hash = self.hash_secret(&passphrase)?;
        let now = Utc::now();
        let mut conn = self.conn().await?;

        diesel::insert_into(credential_passphrase::table)
            .values(&NewCredentialPassphrase {
                identity_id: *identity_id.as_uuid(),
                hash: &hash,
                updated_at: now,
            })
            .on_conflict(credential_passphrase::identity_id)
            .do_update()
            .set((
                credential_passphrase::hash.eq(&hash),
                credential_passphrase::updated_at.eq(now),
            ))
            .execute(&mut conn)
            .await
            .map_err(|e| AuthError::Internal(e.into()))?;

        Ok(passphrase)
    }

    pub async fn verify_passphrase(
        &self,
        identity_id: IdentityId,
        passphrase: &str,
    ) -> Result<(), AuthError> {
        let mut conn = self.conn().await?;
        let row: CredentialPassphraseRow = credential_passphrase::table
            .find(*identity_id.as_uuid())
            .select(CredentialPassphraseRow::as_select())
            .first(&mut conn)
            .await
            .map_err(|e| match e {
                diesel::result::Error::NotFound => AuthError::InvalidCredentials,
                other => AuthError::Internal(other.into()),
            })?;

        self.verify_secret(&row.hash, &Self::canonical_passphrase(passphrase))
    }

    /// Username-keyed passphrase verification for the standalone bypass login
    /// and unauthenticated recovery. Runs the same dummy-hash anti-enumeration
    /// path as `verify_credential` so a missing user is indistinguishable.
    pub async fn verify_passphrase_by_username(
        &self,
        username: &Username,
        passphrase: &str,
    ) -> Result<Identity, AuthError> {
        let mut conn = self.conn().await?;

        let result: Result<(crate::models::IdentityRow, CredentialPassphraseRow), _> =
            crate::schema::identity::table
                .inner_join(credential_passphrase::table)
                .filter(crate::schema::identity::username.eq(username.as_str()))
                .select((
                    crate::models::IdentityRow::as_select(),
                    CredentialPassphraseRow::as_select(),
                ))
                .first(&mut conn)
                .await;

        match result {
            Ok((identity_row, cred_row)) => {
                self.verify_secret(&cred_row.hash, &Self::canonical_passphrase(passphrase))?;
                let identity = crate::identity::row_to_identity(identity_row)?;
                if identity.state == IdentityState::Disabled {
                    return Err(AuthError::IdentityDisabled);
                }
                Ok(identity)
            }
            Err(diesel::result::Error::NotFound) => {
                // Burn comparable time against a dummy hash so presence of a
                // passphrase (or the user) isn't observable via timing.
                let _ = self.verify_secret(&self.dummy_hash(), passphrase);
                Err(AuthError::InvalidCredentials)
            }
            Err(e) => Err(AuthError::Internal(e.into())),
        }
    }

    pub async fn remove_passphrase(&self, identity_id: IdentityId) -> Result<(), AuthError> {
        let mut conn = self.conn().await?;
        diesel::delete(credential_passphrase::table.find(*identity_id.as_uuid()))
            .execute(&mut conn)
            .await
            .map_err(|e| AuthError::Internal(e.into()))?;
        Ok(())
    }

    pub async fn has_passphrase(&self, identity_id: IdentityId) -> Result<bool, AuthError> {
        let mut conn = self.conn().await?;
        let count: i64 = credential_passphrase::table
            .find(*identity_id.as_uuid())
            .count()
            .get_result(&mut conn)
            .await
            .map_err(|e| AuthError::Internal(e.into()))?;
        Ok(count > 0)
    }

    // ---- Step-up + status ---------------------------------------------------

    /// Verify the step-up proof for a sensitive action: the passphrase if the
    /// identity has one, otherwise the current password. Single choke point
    /// for password reset/change and TOTP config changes.
    pub async fn verify_step_up(
        &self,
        identity_id: IdentityId,
        secret: &str,
    ) -> Result<(), AuthError> {
        if self.has_passphrase(identity_id).await? {
            self.verify_passphrase(identity_id, secret).await
        } else {
            let password = Password::new(secrecy::SecretString::from(secret.to_string()))
                .map_err(|_| AuthError::InvalidCredentials)?;
            self.verify_password_by_id(identity_id, &password).await
        }
    }

    pub async fn factor_status(&self, identity_id: IdentityId) -> Result<FactorStatus, AuthError> {
        Ok(FactorStatus {
            has_totp: self.has_totp(identity_id).await?,
            has_passphrase: self.has_passphrase(identity_id).await?,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn wordlist_is_diceware_sized() {
        assert_eq!(WORDLIST.lines().count(), 7776);
    }

    #[test]
    fn canonical_passphrase_folds_whitespace_and_case() {
        assert_eq!(
            Engine::canonical_passphrase("  Abacus   Zoom  Cat "),
            "abacus zoom cat"
        );
    }

    #[test]
    fn totp_matching_step_finds_and_rejects() {
        // RFC-style fixed secret; verify the matched step round-trips.
        let secret = Secret::Encoded("JBSWY3DPEHPK3PXP".to_string())
            .to_bytes()
            .unwrap();
        let totp = Engine::totp_for(secret, "surge".into());
        let now = Utc::now();
        let step = Engine::current_step(now);
        let code = totp.generate(step * TOTP_STEP_SECS);

        assert_eq!(Engine::matching_step(&totp, &code, now), Some(step));
        assert_eq!(Engine::matching_step(&totp, "000000", now), None);
    }
}
